# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sgl/db_HW/DB.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 767)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(340, 230, 721, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.query_gBox = QtWidgets.QGroupBox(self.frame)
        self.query_gBox.setGeometry(QtCore.QRect(10, 10, 591, 171))
        self.query_gBox.setObjectName("query_gBox")
        self.groupBox_4 = QtWidgets.QGroupBox(self.query_gBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 100, 581, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 551, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qu_name_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.qu_name_radioButton.setAutoExclusive(False)
        self.qu_name_radioButton.setObjectName("qu_name_radioButton")
        self.horizontalLayout.addWidget(self.qu_name_radioButton)
        self.qu_category_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.qu_category_radioButton.setAutoExclusive(False)
        self.qu_category_radioButton.setObjectName("qu_category_radioButton")
        self.horizontalLayout.addWidget(self.qu_category_radioButton)
        self.qu_color_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.qu_color_radioButton.setAutoExclusive(False)
        self.qu_color_radioButton.setObjectName("qu_color_radioButton")
        self.horizontalLayout.addWidget(self.qu_color_radioButton)
        self.qu_gender_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.qu_gender_radioButton.setAutoExclusive(False)
        self.qu_gender_radioButton.setObjectName("qu_gender_radioButton")
        self.horizontalLayout.addWidget(self.qu_gender_radioButton)
        self.qu_age_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.qu_age_radioButton.setAutoExclusive(False)
        self.qu_age_radioButton.setObjectName("qu_age_radioButton")
        self.horizontalLayout.addWidget(self.qu_age_radioButton)
        self.qu_equal_age_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.qu_equal_age_comboBox.setObjectName("qu_equal_age_comboBox")
        self.qu_equal_age_comboBox.addItem("")
        self.qu_equal_age_comboBox.addItem("")
        self.qu_equal_age_comboBox.addItem("")
        self.qu_equal_age_comboBox.addItem("")
        self.qu_equal_age_comboBox.addItem("")
        self.qu_equal_age_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.qu_equal_age_comboBox)
        self.qu_price_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.qu_price_radioButton.setAutoExclusive(False)
        self.qu_price_radioButton.setObjectName("qu_price_radioButton")
        self.horizontalLayout.addWidget(self.qu_price_radioButton)
        self.qu_equal_price_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.qu_equal_price_comboBox.setObjectName("qu_equal_price_comboBox")
        self.qu_equal_price_comboBox.addItem("")
        self.qu_equal_price_comboBox.addItem("")
        self.qu_equal_price_comboBox.addItem("")
        self.qu_equal_price_comboBox.addItem("")
        self.qu_equal_price_comboBox.addItem("")
        self.qu_equal_price_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.qu_equal_price_comboBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.query_gBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 548, 50))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 5, 1, 1)
        self.qu_name_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.qu_name_comboBox.setEditable(False)
        self.qu_name_comboBox.setDuplicatesEnabled(True)
        self.qu_name_comboBox.setObjectName("qu_name_comboBox")
        self.gridLayout_2.addWidget(self.qu_name_comboBox, 1, 0, 1, 1)
        self.qu_category_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.qu_category_comboBox.setEditable(False)
        self.qu_category_comboBox.setDuplicatesEnabled(True)
        self.qu_category_comboBox.setObjectName("qu_category_comboBox")
        self.gridLayout_2.addWidget(self.qu_category_comboBox, 1, 1, 1, 1)
        self.qu_age_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.qu_age_comboBox.setEditable(False)
        self.qu_age_comboBox.setDuplicatesEnabled(True)
        self.qu_age_comboBox.setObjectName("qu_age_comboBox")
        self.gridLayout_2.addWidget(self.qu_age_comboBox, 1, 2, 1, 1)
        self.qu_color_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.qu_color_comboBox.setEditable(False)
        self.qu_color_comboBox.setDuplicatesEnabled(True)
        self.qu_color_comboBox.setObjectName("qu_color_comboBox")
        self.gridLayout_2.addWidget(self.qu_color_comboBox, 1, 3, 1, 1)
        self.qu_gender_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.qu_gender_comboBox.setEditable(False)
        self.qu_gender_comboBox.setDuplicatesEnabled(True)
        self.qu_gender_comboBox.setObjectName("qu_gender_comboBox")
        self.gridLayout_2.addWidget(self.qu_gender_comboBox, 1, 4, 1, 1)
        self.qu_price_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.qu_price_comboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.qu_price_comboBox.setEditable(True)
        self.qu_price_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.qu_price_comboBox.setDuplicatesEnabled(True)
        self.qu_price_comboBox.setModelColumn(0)
        self.qu_price_comboBox.setObjectName("qu_price_comboBox")
        self.gridLayout_2.addWidget(self.qu_price_comboBox, 1, 5, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.query_gBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(200, 100, 251, 24))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.qu_res_num_label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.qu_res_num_label.setFont(font)
        self.qu_res_num_label.setStyleSheet("color: rgb(239, 41, 41);")
        self.qu_res_num_label.setObjectName("qu_res_num_label")
        self.horizontalLayout_4.addWidget(self.qu_res_num_label)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(610, 20, 91, 151))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qu_help_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.qu_help_btn.setObjectName("qu_help_btn")
        self.verticalLayout.addWidget(self.qu_help_btn)
        self.qu_pushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.qu_pushButton.setObjectName("qu_pushButton")
        self.verticalLayout.addWidget(self.qu_pushButton)
        self.qu_query_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.qu_query_btn.setObjectName("qu_query_btn")
        self.verticalLayout.addWidget(self.qu_query_btn)
        self.qu_preview_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.qu_preview_btn.setObjectName("qu_preview_btn")
        self.verticalLayout.addWidget(self.qu_preview_btn)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(700, 20, 361, 201))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.statistic_gBox = QtWidgets.QGroupBox(self.frame_2)
        self.statistic_gBox.setGeometry(QtCore.QRect(10, 10, 341, 131))
        self.statistic_gBox.setAutoFillBackground(False)
        self.statistic_gBox.setObjectName("statistic_gBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.statistic_gBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(200, 30, 141, 89))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.eldest_pet_lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.eldest_pet_lineEdit.setReadOnly(True)
        self.eldest_pet_lineEdit.setObjectName("eldest_pet_lineEdit")
        self.gridLayout_3.addWidget(self.eldest_pet_lineEdit, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.eldest_age_lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.eldest_age_lineEdit.setReadOnly(True)
        self.eldest_age_lineEdit.setObjectName("eldest_age_lineEdit")
        self.gridLayout_3.addWidget(self.eldest_age_lineEdit, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.eldest_price_lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.eldest_price_lineEdit.setReadOnly(True)
        self.eldest_price_lineEdit.setObjectName("eldest_price_lineEdit")
        self.gridLayout_3.addWidget(self.eldest_price_lineEdit, 2, 1, 1, 1)
        self.gridLayout_3.setColumnMinimumWidth(0, 5)
        self.gridLayout_3.setColumnMinimumWidth(1, 1)
        self.gridLayout_3.setColumnStretch(0, 5)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.statistic_gBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(12, 32, 171, 89))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.total_dog_no_lineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.total_dog_no_lineEdit.setReadOnly(True)
        self.total_dog_no_lineEdit.setObjectName("total_dog_no_lineEdit")
        self.gridLayout.addWidget(self.total_dog_no_lineEdit, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.total_cat_no_lineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.total_cat_no_lineEdit.setReadOnly(True)
        self.total_cat_no_lineEdit.setObjectName("total_cat_no_lineEdit")
        self.gridLayout.addWidget(self.total_cat_no_lineEdit, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.total_price_lineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.total_price_lineEdit.setReadOnly(True)
        self.total_price_lineEdit.setObjectName("total_price_lineEdit")
        self.gridLayout.addWidget(self.total_price_lineEdit, 2, 1, 1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 160, 191, 27))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sta_help_btn = QtWidgets.QPushButton(self.layoutWidget6)
        self.sta_help_btn.setObjectName("sta_help_btn")
        self.horizontalLayout_2.addWidget(self.sta_help_btn)
        self.sta_obtain_btn = QtWidgets.QPushButton(self.layoutWidget6)
        self.sta_obtain_btn.setObjectName("sta_obtain_btn")
        self.horizontalLayout_2.addWidget(self.sta_obtain_btn)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 4)
        self.layoutWidget7 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(240, 150, 94, 47))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.show_money_label = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.show_money_label.setFont(font)
        self.show_money_label.setStyleSheet("color: rgb(239, 41, 41);")
        self.show_money_label.setAlignment(QtCore.Qt.AlignCenter)
        self.show_money_label.setObjectName("show_money_label")
        self.verticalLayout_2.addWidget(self.show_money_label)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 20, 321, 391))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pet_img_gBox = QtWidgets.QGroupBox(self.frame_3)
        self.pet_img_gBox.setGeometry(QtCore.QRect(20, 10, 281, 301))
        self.pet_img_gBox.setObjectName("pet_img_gBox")
        self.pet_img_label = QtWidgets.QLabel(self.pet_img_gBox)
        self.pet_img_label.setGeometry(QtCore.QRect(20, 30, 251, 261))
        self.pet_img_label.setObjectName("pet_img_label")
        self.layoutWidget8 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(20, 360, 281, 27))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.img_help_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.img_help_btn.setObjectName("img_help_btn")
        self.horizontalLayout_3.addWidget(self.img_help_btn)
        self.img_clear_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.img_clear_btn.setObjectName("img_clear_btn")
        self.horizontalLayout_3.addWidget(self.img_clear_btn)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 3)
        self.img_name_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.img_name_lineEdit.setGeometry(QtCore.QRect(210, 320, 81, 25))
        self.img_name_lineEdit.setReadOnly(True)
        self.img_name_lineEdit.setObjectName("img_name_lineEdit")
        self.layoutWidget9 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget9.setGeometry(QtCore.QRect(30, 320, 168, 27))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.img_pre_btn = QtWidgets.QPushButton(self.layoutWidget9)
        self.img_pre_btn.setObjectName("img_pre_btn")
        self.horizontalLayout_5.addWidget(self.img_pre_btn)
        self.img_post_btn = QtWidgets.QPushButton(self.layoutWidget9)
        self.img_post_btn.setObjectName("img_post_btn")
        self.horizontalLayout_5.addWidget(self.img_post_btn)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(340, 20, 351, 201))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.intro_gBox = QtWidgets.QGroupBox(self.frame_4)
        self.intro_gBox.setGeometry(QtCore.QRect(10, 10, 331, 191))
        self.intro_gBox.setObjectName("intro_gBox")
        self.intro_plainTextEdit = QtWidgets.QPlainTextEdit(self.intro_gBox)
        self.intro_plainTextEdit.setGeometry(QtCore.QRect(0, 30, 331, 151))
        self.intro_plainTextEdit.setReadOnly(True)
        self.intro_plainTextEdit.setObjectName("intro_plainTextEdit")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(340, 430, 721, 281))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.ops_gBox = QtWidgets.QGroupBox(self.frame_5)
        self.ops_gBox.setGeometry(QtCore.QRect(10, 0, 701, 281))
        self.ops_gBox.setObjectName("ops_gBox")
        self.groupBox = QtWidgets.QGroupBox(self.ops_gBox)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 691, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 501, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 6, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 4, 1, 2)
        self.trans_name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.trans_name_lineEdit.setObjectName("trans_name_lineEdit")
        self.gridLayout_4.addWidget(self.trans_name_lineEdit, 1, 0, 1, 1)
        self.trans_age_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.trans_age_lineEdit.setObjectName("trans_age_lineEdit")
        self.gridLayout_4.addWidget(self.trans_age_lineEdit, 1, 3, 1, 1)
        self.trans_color_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.trans_color_lineEdit.setObjectName("trans_color_lineEdit")
        self.gridLayout_4.addWidget(self.trans_color_lineEdit, 1, 4, 1, 1)
        self.trans_gender_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.trans_gender_lineEdit.setObjectName("trans_gender_lineEdit")
        self.gridLayout_4.addWidget(self.trans_gender_lineEdit, 1, 6, 1, 1)
        self.trans_price_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.trans_price_lineEdit.setObjectName("trans_price_lineEdit")
        self.gridLayout_4.addWidget(self.trans_price_lineEdit, 1, 7, 1, 1)
        self.trans_category_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.trans_category_lineEdit.setObjectName("trans_category_lineEdit")
        self.gridLayout_4.addWidget(self.trans_category_lineEdit, 1, 1, 1, 2)
        self.layoutWidget10 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget10.setGeometry(QtCore.QRect(560, 30, 82, 101))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.trans_add_help_btn = QtWidgets.QPushButton(self.layoutWidget10)
        self.trans_add_help_btn.setObjectName("trans_add_help_btn")
        self.verticalLayout_4.addWidget(self.trans_add_help_btn)
        self.trans_clear_btn = QtWidgets.QPushButton(self.layoutWidget10)
        self.trans_clear_btn.setObjectName("trans_clear_btn")
        self.verticalLayout_4.addWidget(self.trans_clear_btn)
        self.trans_add_ok_btn = QtWidgets.QPushButton(self.layoutWidget10)
        self.trans_add_ok_btn.setObjectName("trans_add_ok_btn")
        self.verticalLayout_4.addWidget(self.trans_add_ok_btn)
        self.layoutWidget11 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget11.setGeometry(QtCore.QRect(20, 110, 501, 27))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.trans_load_img_btn = QtWidgets.QPushButton(self.layoutWidget11)
        self.trans_load_img_btn.setObjectName("trans_load_img_btn")
        self.horizontalLayout_7.addWidget(self.trans_load_img_btn)
        self.trans_img_lineEdit = QtWidgets.QLineEdit(self.layoutWidget11)
        self.trans_img_lineEdit.setObjectName("trans_img_lineEdit")
        self.horizontalLayout_7.addWidget(self.trans_img_lineEdit)
        self.trans_preview_btn = QtWidgets.QPushButton(self.layoutWidget11)
        self.trans_preview_btn.setObjectName("trans_preview_btn")
        self.horizontalLayout_7.addWidget(self.trans_preview_btn)
        self.groupBox_2 = QtWidgets.QGroupBox(self.ops_gBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 511, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget12 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget12.setGeometry(QtCore.QRect(10, 30, 491, 60))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 0, 1, 1)
        self.trans_sell_pet_name_comboBox = QtWidgets.QComboBox(self.layoutWidget12)
        self.trans_sell_pet_name_comboBox.setObjectName("trans_sell_pet_name_comboBox")
        self.gridLayout_5.addWidget(self.trans_sell_pet_name_comboBox, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 2, 1, 1)
        self.trans_sell_price_lineEdit = QtWidgets.QLineEdit(self.layoutWidget12)
        self.trans_sell_price_lineEdit.setReadOnly(True)
        self.trans_sell_price_lineEdit.setObjectName("trans_sell_price_lineEdit")
        self.gridLayout_5.addWidget(self.trans_sell_price_lineEdit, 0, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 0, 1, 1)
        self.trans_sell_check_btn = QtWidgets.QPushButton(self.layoutWidget12)
        self.trans_sell_check_btn.setObjectName("trans_sell_check_btn")
        self.gridLayout_5.addWidget(self.trans_sell_check_btn, 1, 2, 1, 2)
        self.trans_sell_category_lineEdit = QtWidgets.QLineEdit(self.layoutWidget12)
        self.trans_sell_category_lineEdit.setReadOnly(True)
        self.trans_sell_category_lineEdit.setObjectName("trans_sell_category_lineEdit")
        self.gridLayout_5.addWidget(self.trans_sell_category_lineEdit, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 0, 1, 1)
        self.trans_sell_buyer_comboBox = QtWidgets.QComboBox(self.layoutWidget12)
        self.trans_sell_buyer_comboBox.setObjectName("trans_sell_buyer_comboBox")
        self.gridLayout_6.addWidget(self.trans_sell_buyer_comboBox, 0, 1, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 1, 0, 1, 2)
        self.trans_sell_final_price_lineEdit = QtWidgets.QLineEdit(self.layoutWidget12)
        self.trans_sell_final_price_lineEdit.setObjectName("trans_sell_final_price_lineEdit")
        self.gridLayout_6.addWidget(self.trans_sell_final_price_lineEdit, 1, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.trans_sell_help_btn = QtWidgets.QPushButton(self.layoutWidget12)
        self.trans_sell_help_btn.setObjectName("trans_sell_help_btn")
        self.verticalLayout_3.addWidget(self.trans_sell_help_btn)
        self.trans_sell_ok_btn = QtWidgets.QPushButton(self.layoutWidget12)
        self.trans_sell_ok_btn.setObjectName("trans_sell_ok_btn")
        self.verticalLayout_3.addWidget(self.trans_sell_ok_btn)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.ops_gBox)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 180, 171, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget13 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget13.setGeometry(QtCore.QRect(10, 30, 151, 58))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget13)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 0, 0, 1, 1)
        self.trans_del_pet_name_comboBox = QtWidgets.QComboBox(self.layoutWidget13)
        self.trans_del_pet_name_comboBox.setObjectName("trans_del_pet_name_comboBox")
        self.gridLayout_7.addWidget(self.trans_del_pet_name_comboBox, 0, 1, 1, 1)
        self.trans_del_load_btn = QtWidgets.QPushButton(self.layoutWidget13)
        self.trans_del_load_btn.setObjectName("trans_del_load_btn")
        self.gridLayout_7.addWidget(self.trans_del_load_btn, 1, 0, 1, 1)
        self.trans_del_ok_btn = QtWidgets.QPushButton(self.layoutWidget13)
        self.trans_del_ok_btn.setObjectName("trans_del_ok_btn")
        self.gridLayout_7.addWidget(self.trans_del_ok_btn, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(10, 430, 321, 281))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.intro_gBox_2 = QtWidgets.QGroupBox(self.frame_6)
        self.intro_gBox_2.setGeometry(QtCore.QRect(10, 10, 301, 271))
        self.intro_gBox_2.setObjectName("intro_gBox_2")
        self.his_textEdit = QtWidgets.QTextEdit(self.intro_gBox_2)
        self.his_textEdit.setGeometry(QtCore.QRect(10, 30, 281, 231))
        self.his_textEdit.setReadOnly(True)
        self.his_textEdit.setObjectName("his_textEdit")
        self.back_frame = QtWidgets.QFrame(self.centralwidget)
        self.back_frame.setGeometry(QtCore.QRect(0, 0, 1091, 741))
        self.back_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_frame.setObjectName("back_frame")
        self.frame_7 = QtWidgets.QFrame(self.back_frame)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1091, 741))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.back_frame.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.query_gBox.setToolTip(_translate("MainWindow", "pet attributes"))
        self.query_gBox.setTitle(_translate("MainWindow", "Query"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Choice"))
        self.qu_name_radioButton.setText(_translate("MainWindow", "Name"))
        self.qu_category_radioButton.setText(_translate("MainWindow", "Category"))
        self.qu_color_radioButton.setText(_translate("MainWindow", "Color"))
        self.qu_gender_radioButton.setText(_translate("MainWindow", "Gender"))
        self.qu_age_radioButton.setText(_translate("MainWindow", "Age"))
        self.qu_equal_age_comboBox.setItemText(0, _translate("MainWindow", ">"))
        self.qu_equal_age_comboBox.setItemText(1, _translate("MainWindow", "="))
        self.qu_equal_age_comboBox.setItemText(2, _translate("MainWindow", "<"))
        self.qu_equal_age_comboBox.setItemText(3, _translate("MainWindow", ">="))
        self.qu_equal_age_comboBox.setItemText(4, _translate("MainWindow", "<="))
        self.qu_equal_age_comboBox.setItemText(5, _translate("MainWindow", "!="))
        self.qu_price_radioButton.setText(_translate("MainWindow", "Price"))
        self.qu_equal_price_comboBox.setItemText(0, _translate("MainWindow", ">"))
        self.qu_equal_price_comboBox.setItemText(1, _translate("MainWindow", "="))
        self.qu_equal_price_comboBox.setItemText(2, _translate("MainWindow", "<"))
        self.qu_equal_price_comboBox.setItemText(3, _translate("MainWindow", ">="))
        self.qu_equal_price_comboBox.setItemText(4, _translate("MainWindow", "<="))
        self.qu_equal_price_comboBox.setItemText(5, _translate("MainWindow", "!="))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Category"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.label_5.setText(_translate("MainWindow", "Color"))
        self.label_4.setText(_translate("MainWindow", "Gender"))
        self.label_9.setText(_translate("MainWindow", "Price"))
        self.label_25.setText(_translate("MainWindow", "RESULT number:"))
        self.qu_res_num_label.setText(_translate("MainWindow", "0"))
        self.qu_help_btn.setText(_translate("MainWindow", "help"))
        self.qu_pushButton.setText(_translate("MainWindow", "Load"))
        self.qu_query_btn.setText(_translate("MainWindow", "Query"))
        self.qu_preview_btn.setText(_translate("MainWindow", "Preview"))
        self.statistic_gBox.setTitle(_translate("MainWindow", "Pets Statistic"))
        self.label_10.setText(_translate("MainWindow", "Eldest Pet"))
        self.label_11.setText(_translate("MainWindow", "Eldest Age"))
        self.label_12.setText(_translate("MainWindow", " Price"))
        self.label_6.setText(_translate("MainWindow", "Number of Dog"))
        self.label_7.setText(_translate("MainWindow", "Number of Cat"))
        self.label_8.setText(_translate("MainWindow", "Total Price"))
        self.sta_help_btn.setText(_translate("MainWindow", "help"))
        self.sta_obtain_btn.setText(_translate("MainWindow", "Obtain"))
        self.label_26.setText(_translate("MainWindow", "Total Money :"))
        self.show_money_label.setText(_translate("MainWindow", "0"))
        self.pet_img_gBox.setTitle(_translate("MainWindow", "Pet Image:"))
        self.pet_img_label.setText(_translate("MainWindow", "pet pic show here"))
        self.img_help_btn.setText(_translate("MainWindow", "help"))
        self.img_clear_btn.setText(_translate("MainWindow", "clear"))
        self.img_pre_btn.setText(_translate("MainWindow", "<"))
        self.img_post_btn.setText(_translate("MainWindow", ">"))
        self.intro_gBox.setTitle(_translate("MainWindow", "Introduction"))
        self.intro_plainTextEdit.setPlainText(_translate("MainWindow", "Pet Management System helps pet store holders to manage information of all dogs and cats in the store and trade with other holders.\n"
""))
        self.ops_gBox.setTitle(_translate("MainWindow", "Transaction"))
        self.groupBox.setTitle(_translate("MainWindow", "Add"))
        self.label_18.setText(_translate("MainWindow", "Category"))
        self.label_13.setText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "Gender"))
        self.label_16.setText(_translate("MainWindow", "Age"))
        self.label_15.setText(_translate("MainWindow", "Price"))
        self.label_17.setText(_translate("MainWindow", "Color"))
        self.trans_name_lineEdit.setPlaceholderText(_translate("MainWindow", "aaa"))
        self.trans_age_lineEdit.setPlaceholderText(_translate("MainWindow", "11"))
        self.trans_color_lineEdit.setPlaceholderText(_translate("MainWindow", "yellow"))
        self.trans_gender_lineEdit.setPlaceholderText(_translate("MainWindow", "male"))
        self.trans_price_lineEdit.setPlaceholderText(_translate("MainWindow", "12"))
        self.trans_category_lineEdit.setPlaceholderText(_translate("MainWindow", "dog/cat"))
        self.trans_add_help_btn.setText(_translate("MainWindow", "help"))
        self.trans_clear_btn.setText(_translate("MainWindow", "clear"))
        self.trans_add_ok_btn.setText(_translate("MainWindow", "OK"))
        self.trans_load_img_btn.setText(_translate("MainWindow", "Load Image"))
        self.trans_preview_btn.setText(_translate("MainWindow", "Preview"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sell"))
        self.label_20.setText(_translate("MainWindow", "Name"))
        self.label_21.setText(_translate("MainWindow", "Price"))
        self.label_22.setText(_translate("MainWindow", "Category"))
        self.trans_sell_check_btn.setText(_translate("MainWindow", "Check"))
        self.label_19.setText(_translate("MainWindow", "Buyer"))
        self.label_23.setText(_translate("MainWindow", "Final Price"))
        self.trans_sell_help_btn.setText(_translate("MainWindow", "help"))
        self.trans_sell_ok_btn.setText(_translate("MainWindow", "OK"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Delete"))
        self.label_24.setText(_translate("MainWindow", "Name"))
        self.trans_del_load_btn.setText(_translate("MainWindow", "load"))
        self.trans_del_ok_btn.setText(_translate("MainWindow", "OK"))
        self.intro_gBox_2.setTitle(_translate("MainWindow", "History"))
import add_rc
